from typing import List, Optional
from sqlmodel import  select
from sqlmodel.ext.asyncio.session import AsyncSession
from model.models import Product
from schema import ProductCreate, ProductRead
from sqlalchemy.orm import selectinload # to avoid the error of lazy loading when we try to access the category and reviews of the created product after commit, because they are not loaded in the session after commit, so we need to load them in the session after commit to avoid the error of lazy loading when we try to access them after commit

async def create_product(product_data:ProductCreate, session: AsyncSession)->Product:
    
    db_product = Product.model_validate(product_data)
    
    session.add(db_product)
    await session.commit()
    # if not handled, it will genetate an error when we try to access the id of the created product because it is not refreshed in the session after commit, so we need to refresh it to get the id and other fields that are generated by the database after commit
    # we need to add selectinload to the relationship fields in the product model to avoid the error of lazy loading when we try to access the category and reviews of the created product after commit, because they are not loaded in the session after commit, so we need to load them in the session after commit to avoid the error of lazy loading when we try to access them after commit
    
    await session.refresh(db_product)
    exec_statement = select(Product).options(selectinload(Product.category), selectinload(Product.reviews)).where(Product.id == db_product.id)
    egar_load = await session.exec(exec_statement)
    db_product = egar_load.one()
    return db_product


async def get_all_products(session: AsyncSession)->List[Product]:
    # implement the eager loading for the category and reviews of the products to avoid the error of lazy loading when we try to access the category and reviews of the products because they are not loaded in the session after commit, so we need to load them in the session after commit to avoid the error of lazy loading when we try to access them after commit
    
   statement = select(Product).options(selectinload(Product.category), selectinload(Product.reviews))
   result = await session.exec(statement)
   return result.all() # type: ignore

async def get_product_by_id(product_id: int, session: AsyncSession)-> Optional[Product]:
    statement = select(Product).options(selectinload(Product.category), selectinload(Product.reviews)).where(Product.id == product_id)
    result = await session.exec(statement)
    return result.one_or_none()




